[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 - %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonYesToAll=全部是(&A)
ButtonNo=否(&N)
ButtonNoToAll=全部否(&O)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)...
ButtonWizardBrowse=浏览(&R)...
ButtonNewFolder=新建文件夹(&M)
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装时使用的语言。
ClickNext=点击“下一步”继续，或点击“取消”退出安装。
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=即将在你的电脑上安装 [name/ver]。%n%n已包含运行环境，无需单独安装 Python、Node.js 或浏览器组件。
WizardSelectDir=选择安装位置
SelectDirDesc=将 [name] 安装到哪里？
SelectDirLabel3=程序将安装到以下文件夹。
SelectDirBrowseLabel=点击“下一步”继续；需要更改目录时点击“浏览”。
DiskSpaceGBLabel=至少需要 [gb] GB 可用空间。
DiskSpaceMBLabel=至少需要 [mb] MB 可用空间。
DirExistsTitle=目录已存在
DirExists=目录：%n%n%1%n%n已经存在。是否安装到该目录？
DirDoesntExistTitle=目录不存在
DirDoesntExist=目录：%n%n%1%n%n不存在。是否创建？
WizardSelectTasks=选择附加任务
SelectTasksDesc=希望安装程序执行哪些附加任务？
SelectTasksLabel2=请选择附加任务，然后点击“下一步”。
WizardReady=准备安装
ReadyLabel1=现在可以开始安装 [name]。
ReadyLabel2a=点击“安装”继续，或点击“上一步”修改设置。
ReadyMemoDir=安装位置：
ReadyMemoTasks=附加任务：
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
StatusExtractFiles=正在释放程序文件...
StatusCreateIcons=正在创建快捷方式...
StatusRunProgram=正在完成安装...
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=程序已安装到你的电脑。%n%n点击“完成”关闭安装向导。
FinishedLabel=程序已安装到你的电脑，可通过创建的快捷方式启动。%n%n点击“完成”关闭安装向导。
ClickFinish=点击“完成”退出安装。
RunEntryExec=启动 %1
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成，现在退出将无法使用程序。%n%n是否退出安装？
UninstallConfirm=是否卸载 %1 及其程序组件？
UninstallStatusLabel=正在卸载 %1，请稍候。
UninstalledAll=%1 已卸载完成。
